pipeline:
  scripts:
    image: bravissimolabs/alpine-git
    commands:
      - git clone https://github.com/openscopeproject/InteractiveHtmlBom.git

  publish:
    image: plugins/docker
    repo: surgecloud/drone-kicad-ibom
    #registry: drone.io
    tags: [edge]
    when:
      branch: feature/*
      event: deployment
      environment: staging
    secrets: [docker_username, docker_password]

  publish:
    image: plugins/docker
    repo: surgecloud/drone-kicad-ibom
    tags: [latest, 0.0.2]
    when:
      branch: master
    secrets: [docker_username, docker_password]
